/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-primary': '#ffffff',
        'tertiary-container': '#85675c',
        'tertiary-fixed-dim': '#e4beb2',
        surface: '#f5fced',
        'surface-container-low': '#eff6e7',
        'outline-variant': '#bfcaba',
        secondary: '#00639a',
        'on-primary-fixed-variant': '#0c5216',
        'primary-fixed': '#acf4a4',
        'on-error': '#ffffff',
        'on-surface': '#171d14',
        'on-secondary-fixed-variant': '#004a75',
        'on-tertiary-container': '#ffeee8',
        'on-secondary-fixed': '#001d32',
        'error-container': '#ffdad6',
        'surface-container': '#e9f0e1',
        'on-background': '#171d14',
        'inverse-primary': '#91d78a',
        'tertiary-fixed': '#ffdbce',
        tertiary: '#6b4f45',
        'surface-tint': '#2a6b2c',
        'secondary-container': '#51b2fe',
        'on-tertiary-fixed-variant': '#5b4137',
        'on-tertiary': '#ffffff',
        outline: '#707a6c',
        'on-primary-container': '#cbffc2',
        'surface-container-high': '#e3ebdc',
        'surface-variant': '#dee5d6',
        'primary-container': '#3a7b3a',
        'surface-container-lowest': '#ffffff',
        'on-error-container': '#93000a',
        'on-primary-fixed': '#002203',
        'secondary-fixed': '#cee5ff',
        primary: '#206223',
        background: '#f5fced',
        'inverse-on-surface': '#ecf3e4',
        'secondary-fixed-dim': '#96ccff',
        'on-secondary-container': '#00436a',
        'surface-bright': '#f5fced',
        error: '#ba1a1a',
        'primary-fixed-dim': '#91d78a',
        'on-secondary': '#ffffff',
        'surface-container-highest': '#dee5d6',
        'surface-dim': '#d5dcce',
        'on-surface-variant': '#40493d',
        'on-tertiary-fixed': '#2b160f',
        'inverse-surface': '#2c3228',
        'secondary-container-dark': '#51b2fe',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        xxl: '1.5rem',
      },
    },
  },
  plugins: [],
}
